name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      
      - run: yarn install --frozen-lockfile
      
      - name: Run tests
        run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest

    needs: [test]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      
      - name: Build app
        run: yarn build
    
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}

      - name: Deploy with ssh
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
            docker stop myapp || true
            docker rm myapp || true
            docker run -d -p 80:3000 --name myapp ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
      
